rates:
  daily_salary: 600.0
  overtime_hourly_rate: 75.0
  night_diff_multiplier: 0.1

shifts:
  shift_1: {in: "06:00", out: "14:00"}
  shift_2: {in: "14:00", out: "22:00"}
  shift_3: {in: "22:00", out: "06:00"}

deductions:
  sss_rate: 0.045
  phil_health_rate: 0.04
  pag_ibig_rate: 0.02


